spring.application.name=url-shortner

#spring.datasource.url=${DB_URL}
spring.datasource.url=jdbc:postgresql://ep-wispy-thunder-aqzansab-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
#spring.datasource.username=${DB_USERNAME}
spring.datasource.username=neondb_owner
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.password=npg_nfBhNRZ9e0Iw

spring.data.redis.host=localhost
spring.data.redis.port=6380

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 